language: node_js
sudo: false
dist: trusty
node_js:
    - '8.9.1'
install: "pip install -r requirements.txt"
script:
    - ./scripts/ci/build.sh
    - ./scripts/ci/test.sh
    - ./scripts/ci/deploy.sh
    - ./scripts/ci/angular.sh
    - ./scripts/ci/cleanup.sh
    - ./scripts/ci/print-logs.sh